### ISSUE TITLE
sbt revolver link is not found

### ISSUE THREAD

**Issue by G-yhlee** [spray/sbt-revolver#112] opened 2023-04-07 07:55 UTC
https://repo1.maven.org/maven2/io/spray
https://repo1.maven.org/maven2/io/spray/sbt-revolver_2.12_1.0/0.9.1/sbt-revolver-0.9.1.pom

In this directory, there is no sbt-revolver
Maybe Link has been deleted. what happened?

```md
cmd ) sbt
...
[error] sbt.librarymanagement.ResolveException: Error downloading io.spray:sbt-revolver;sbtVersion=1.0;scalaVersion=2.12:0.9.1
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/io/spray/sbt-revolver_2.12_1.0/0.9.1/sbt-revolver-0.9.1.pom
[error]   not found: /home/lmchain2/.ivy2/localio.spray/sbt-revolver/scala_2.12/sbt_1.0/0.9.1/ivys/ivy.xml
[error]   checksum format error: /home/lmchain2/.cache/coursier/v1/https/repo.scala-sbt.org/scalasbt/sbt-plugin-releases/io.spray/sbt-revolver/scala_2.12/sbt_1.0/0.9.1/ivys/ivy.xml.sha1
```

**Comment by raboof** [comment] 2023-04-07 08:00
This seems like a duplicate of #110 : it's expected that the artifacts are not present at repo1.maven.org, but we'd expect sbt to find them at https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases .

Perhaps there's something wrong with your previously-downloaded `/home/lmchain2/.cache/coursier/v1/https/repo.scala-sbt.org/scalasbt/sbt-plugin-releases/io.spray/sbt-revolver/scala_2.12/sbt_1.0/0.9.1` directory, could you remove that and try again? If the problem persists, could you share the contents of `/home/lmchain2/.cache/coursier/v1/https/repo.scala-sbt.org/scalasbt/sbt-plugin-releases/io.spray/sbt-revolver/scala_2.12/sbt_1.0/0.9.1/ivys/ivy.xml.sha1`?

**Comment by KannarFr** [comment] 2023-04-07 11:02
@raboof well looks you need to check https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases. 

```
Time flies when you’re having fun.
Your 14-day trial may be over, but you have options!
Need help choosing the right subscription or additional time on your trial? Just let us know and a DevOps expert will reach out to assist you.
```

**Comment by raboof** [comment] 2023-04-07 11:48
Ah, that's not good ;) - looks like it's being investigated: https://twitter.com/scala_sbt/status/1644179045469356033

**Comment by raboof** [comment] 2023-04-07 12:08
(closing this here since this problem is clearly wider than just sbt-revolver)

**Closed by raboof** 2023-04-07 12:08 UTC

**Comment by mkurz** [comment] 2023-04-07 21:09
This library is only hosted on repo.scala-sbt.org currently and should get published to Maven central instead e.g. using sbt-ci-release. We never know when repo.scala-sbt.org will not be available anymore.
