### ISSUE TITLE
scala library missing if re-start

### ISSUE THREAD

**Issue by MikaelMayer** [spray/sbt-revolver#51] opened 2015-09-02 16:56 UTC
## Problem:

Create a project using scala 2.11.7 and SBT 0.13.9 and add the sbt-revolver plugin to it.

Create a main file which displays the value of 

```scala
scala.Predef.getClass.getProtectionDomain.getCodeSource
```

Launch the command `re-start` on it.

## Expected print

`(file:/(...)/.ivy2/cache/org.scala-lang/scala-library/jars/scala-libra
ry-2.11.7.jar <no signer certificates>)`

Something not null. If we launched the main function with the command `run`, the result would be the expected one.

## Actual print

**null**

**Comment by jrudolph** [comment] 2015-09-03 08:13
The library is not missing but is being put into the boot classpath which leads to the observed behavior. This seems to be a duplicate of #46.

**Comment by MikaelMayer** [comment] 2015-09-03 08:49
My problem comes from some kind of reflection:
In the new thread #51 I explain this (you saw it)

Since I am dealing with a sub-project (scala-js with spray), what I tried to do is the following (in `build.sbt` at the root level)

    .jvmSettings(
        Revolver.settings:_*
    )
    .jvmSettings(
        fullClasspath in Revolver.reStart <<= fullClasspath in Runtime,
    )

But this does not solve the problem of #51. Same if I replace the second line by this in the `build.sbt` at the root level.

    .jvmSettings(
        fullClasspath in Revolver.reStart <<= fullClasspath in Compile,
    )

Is there any other variables I can try to change? Even debugging with `.jvmSettings(Revolver.enableDebugging(port = 9999, suspend = true))` prevents the application to start (but that may be another unrelated problem)

**Comment by MikaelMayer** [comment] 2015-09-03 09:16
I created a minimal github project with documentation to recreate this issue.

https://github.com/MikaelMayer/SbtRevolverFails

**Comment by jrudolph** [comment] 2015-09-03 09:21
Have you seen my explanation above? This will probably be fixed when we fix #46 which will add an option to put the Scala library into the normal classpath instead of the boot classpath.

**Comment by MikaelMayer** [comment] 2015-09-03 09:28
I did not see the link between the two, but I trust you.

In the meanwhile, I'm using run and I'll create some scripts to restart the tasks.

Best of luck to fix this issue.

**Comment by jrudolph** [comment] 2015-09-05 07:59
This should be fixed with the upcoming version 0.8.0-RC1 which fixes #46.

**Closed by jrudolph** 2015-09-05 07:59 UTC

**Comment by MikaelMayer** [comment] 2015-09-07 10:35
It is fixed with this version !
I added:the following to `projects/build.sbt` which is the latest version at the writing of this post.

    lazy val root = project.in(file(".")).dependsOn(sbtrevolver) 

    lazy val sbtrevolver = RootProject(uri("https://github.com/spray/sbt-revolver.git#3213519c0e0ecc7d687cbdab1ed8dec66699d346"))

and now `re-start` works as expected. Thank you !
